In [1]:
import torch

In [2]:
weights = torch.ones(4, requires_grad=True)

num_epochs = 3

for epoch in range(num_epochs):
    model_output = (weights * 3).sum()

    model_output.backward()

    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [5]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
# z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor([ 0.0893, -0.3475, -0.6112], requires_grad=True)
tensor([2.0893, 1.6525, 1.3888], grad_fn=<AddBackward0>)
tensor([8.7302, 5.4615, 3.8575], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs