In [1]:
import torch

In [2]:
x = torch.rand([3,4])
x

tensor([[0.2673, 0.1811, 0.5807, 0.5528],
        [0.9949, 0.1797, 0.1581, 0.2061],
        [0.0740, 0.0654, 0.9874, 0.0095]])

In [3]:
x = torch.ones([2,4,5], dtype=torch.int)
x

tensor([[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]], dtype=torch.int32)

In [4]:
x.size()

torch.Size([2, 4, 5])

In [15]:
x = torch.rand([2,2])
y = torch.tensor([[1., 2.],
                  [3., 4.]])
print(x)
print(y)
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)

tensor([[0.4834, 0.8997],
        [0.0935, 0.4269]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.4834, 2.8997],
        [3.0935, 4.4269]])
tensor([[-0.5166, -1.1003],
        [-2.9065, -3.5731]])
tensor([[0.4834, 1.7994],
        [0.2806, 1.7078]])
tensor([[0.4834, 0.4499],
        [0.0312, 0.1067]])
tensor([[0., 0.],
        [0., 0.]])


In [16]:
print(x)
print(y)
print(y.add(x))
print(y)

tensor([[0.4834, 0.8997],
        [0.0935, 0.4269]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.4834, 2.8997],
        [3.0935, 4.4269]])
tensor([[1., 2.],
        [3., 4.]])


In [17]:
print(x)
print(y)
print(y.add_(x))
print(y) # in place add, y changed

tensor([[0.4834, 0.8997],
        [0.0935, 0.4269]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.4834, 2.8997],
        [3.0935, 4.4269]])
tensor([[1.4834, 2.8997],
        [3.0935, 4.4269]])


In [21]:
x = torch.rand([5,3])
print(x)
print(x[0,1]) # get item
print(x[0,1].item()) # value itself

print(x[:,1:]) # 2d slicing
print(x[:,1]) # 1d slicing

tensor([[0.7762, 0.4943, 0.7641],
        [0.2069, 0.0629, 0.2495],
        [0.1715, 0.0488, 0.9812],
        [0.3359, 0.0802, 0.9957],
        [0.5422, 0.5259, 0.2391]])
tensor(0.4943)
0.4942890405654907
tensor([[0.4943, 0.7641],
        [0.0629, 0.2495],
        [0.0488, 0.9812],
        [0.0802, 0.9957],
        [0.5259, 0.2391]])
tensor([0.4943, 0.0629, 0.0488, 0.0802, 0.5259])


In [26]:
x = torch.rand([4,4])
print(x)
print(x.view([16]))
print(x.view([-1,8]))

tensor([[0.9977, 0.8375, 0.5343, 0.9318],
        [0.3550, 0.0146, 0.6865, 0.7605],
        [0.5806, 0.6441, 0.8835, 0.0227],
        [0.6587, 0.9419, 0.0788, 0.9637]])
tensor([0.9977, 0.8375, 0.5343, 0.9318, 0.3550, 0.0146, 0.6865, 0.7605, 0.5806,
        0.6441, 0.8835, 0.0227, 0.6587, 0.9419, 0.0788, 0.9637])
tensor([[0.9977, 0.8375, 0.5343, 0.9318, 0.3550, 0.0146, 0.6865, 0.7605],
        [0.5806, 0.6441, 0.8835, 0.0227, 0.6587, 0.9419, 0.0788, 0.9637]])


In [27]:
import numpy as np

In [29]:
a = torch.ones([5,2])
print(a)

b = a.numpy()  # tensor to numpy
print(b)

a.add_(torch.rand([5,2]))
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1.1130, 1.6049],
        [1.3475, 1.3144],
        [1.4007, 1.6358],
        [1.2177, 1.3599],
        [1.1473, 1.5748]])
[[1.1130005 1.6049088]
 [1.3474811 1.3144455]
 [1.4006822 1.6357667]
 [1.2176868 1.3599203]
 [1.147335  1.5747514]]


In [30]:
a = np.ones([5,2])
print(a)

b = torch.from_numpy(a)
print(b)

a += 1

print(a)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], dtype=torch.float64)


In [31]:
torch.cuda.is_available()
device = torch.device("cuda") # tensor on GPU

a = torch.ones([2,5], device=device)

print(a)

b = a.numpy() # can't convert GPU based tensor to CPU based numpy
print(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [32]:
a = torch.ones([2,5])
a = a.to(device) # can't convert GPU based tensor to CPU based numpy
print(a)

# a = a.to("cpu")
b = a.numpy()
print(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')


TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [33]:
a = torch.ones([2,5])
a = a.to(device)
print(a)

a = a.to("cpu") # convert back to CPU
b = a.numpy()
print(b)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
